spring.application.name=SportsTournamentManager

spring.datasource.url=jdbc:postgresql://localhost:5432/deportivos
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/database.sql

