spring.application.name=SportsTournamentManager

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:deportivos}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/database.sql

# ===================================
# Initialization Configuration
# ===================================
app.init.enabled=true
app.init.master-username=${MASTER_USERNAME:admin}
app.init.master-email=${MASTER_EMAIL:admin@sportstournament.com}
app.init.master-password=${MASTER_PASSWORD:admin123}
